export const CASBIN_ENFORCER = 'CASBIN_ENFORCER';
export const NEST_CASBIN_OPTION = 'NEST_CASBIN_OPTION';
export const NEST_CASBIN_MODULE_ID = 'OrmModuleId';
export const DEFAULT_CONNECTION_NAME = 'default';

export const CASBIN_OPTIONS = 'CASBIN_OPTIONS';
export const CASBIN_ADAPTER = 'CASBIN_ADAPTER';
